title: Transcribe Edge
description: On-device meeting notes for iPhone
url: https://yoshitetsu.github.io
baseurl: /transcribe-legal
theme: minima
permalink: pretty
header_pages:
  - terms/index.md
  - privacy/index.md
author: Tetsuhiro Yoshida
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
include:
  - googled216a0b960e76e4b.html
